### ISSUE TITLE
Export keccakf function

### ISSUE THREAD

**Issue by roosmaa** [ebfe/keccak#2]
What do you think of making the `keccakf` function publicly callable? It would be useful to enable sponge based random number generation.

**Comment by gvanas** [comment]
Dear Mart,

I think that the Keccak-f permutation should remain private, while the sponge and duplex constructions on top of it should be public.

If you want to use Keccak as a pseudo-random number generator, the best would be to implement it via the duplex construction. See [Section 6.1 of our paper on duplexing](http://sponge.noekeon.org/SpongeDuplex.pdf) for more details.

Kind regards,
Gilles, for the Keccak team

**Comment by roosmaa** [comment]
I was porting over Monero's crypto functionality [to Go](http://godoc.org/github.com/roosmaa/go-monero/crypto) the other day and the [pRNG code there](https://github.com/monero-project/bitmonero/blob/master/src/crypto/random.c#L116) used [keccakf directly](https://github.com/monero-project/bitmonero/blob/master/src/crypto/hash.c#L38). That's why I thought to suggest making this method public. But if you think it should remain private, so be it :+1: 

My take away from this is that Monero's code uses it in an exotic way (hopefully it doesn't compromise on the security?). Anyway, I needed to reimplement it to test my implementation against test data which relies on this kind of pRNG. I've embedded the library for the time being to replicate that.
